### ISSUE TITLE
Ampliación de la clase Fraction: Incluir métodos multiply() y divide()

### ISSUE THREAD

**Issue by albertogarciag95** [albertogarciag95/IWVG.SwC.Alberto#4]
Más información en la [wiki](https://github.com/albertogarciag95/IWVG.SwC.Alberto/wiki#issue-6)

**Comment by albertogarciag95** [comment]
Perdón. El enlace a la wiki es erróneo. [Este](https://github.com/albertogarciag95/IWVG.SwC.Alberto/wiki#issue-4) es el correcto. Un saludo.

**Comment by alexph9** [comment]
Done!
